version: '3'
services:
  backend:
    build: .
    container_name: quickmeet-backend
    ports:
      - "3000:3000"
    networks:
      - quickmeet-network
    depends_on:
      - mongo
      - postgres
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:5.0
    container_name: quickmeet-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - quickmeet-network

  postgres:
    image: postgres:14
    container_name: quickmeet-postgres
    environment:
      POSTGRES_USER: quickmeet
      POSTGRES_PASSWORD: quickmeetpass
      POSTGRES_DB: quickmeetdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - quickmeet-network

  redis:
    image: redis:alpine
    container_name: quickmeet-redis
    ports:
      - "6379:6379"
    networks:
      - quickmeet-network

networks:
  quickmeet-network:
    driver: bridge

volumes:
  mongo-data:
  postgres-data:
