### Register a User
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "password123",
  "role": "Organizer"
}

### Login a User
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "password123"
}
